spring.application.name=cenifex

spring.datasource.url=jdbc:mysql://localhost:3306/cenifex
spring.datasource.username=root
spring.datasource.password=mydatabse
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

razorpay.key.id=rzp_test_SVAdkq4MZHrKZC
razorpay.key.secret=IPWU9hRTl1Z6XvkPYL61IZTt
